server.port=8081

# Kafka Configuration
spring.kafka.bootstrap-servers=kafka.egt-digital.com:9192
spring.kafka.security.protocol=SASL_SSL
spring.kafka.sasl.mechanism=SCRAM-SHA-512
spring.kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="dream-mx-readonly" password="odpfeDFGPIU345782#$%^&";
spring.kafka.properties.socket.timeout.ms=30000
spring.kafka.properties.connections.max.idle.ms=540000
spring.kafka.consumer.auto-offset-reset=earliest